---
title: "p8105_hw2_qz2266"
author: "Qing Zhou"
date: "2022-10-05"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, message = FALSE)
```

```{r libraries}
library(tidyverse)
library(readxl)
```

# Problem 2

## Read and clean the Mr. Trash Wheel sheet.

```{r}
mr_trash_wheel = 
  read_excel("data/Trash Wheel Collection data-new.xlsx", 
  sheet = "Mr. Trash Wheel", 
  range =  cell_cols("A:N"), skip = 1) %>% 
  
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(sports_balls = as.integer(round(sports_balls, digits = 0)),year = as.integer(year))
  
```

## Read and clean the Professor Trash Wheel sheet.

```{r}
prof_trash_wheel = 
  read_excel("data/Trash Wheel Collection data-new.xlsx", 
  sheet = "Professor Trash Wheel", 
  range =  cell_cols("A:M"), skip = 1) %>% 
  
  janitor::clean_names() %>% 
  drop_na(dumpster) 
```

## Add a new variable to keep track of which Trash Wheel is which.

```{r}
mr_trash_wheel_new = mutate(mr_trash_wheel, trash_wheel_type = "Mr.") %>%
                     relocate(trash_wheel_type, .before = dumpster) 
                     
prof_trash_wheel_new = mutate(prof_trash_wheel, trash_wheel_type = "Prof.") %>% 
                       relocate(trash_wheel_type, .before = dumpster) 
```                       

## Combine two datasets

```{r}
trash_wheel = 
  bind_rows(mr_trash_wheel_new, prof_trash_wheel_new)
```